language: c 
compiler:
  - gcc
before_install:
  - sudo apt-get update 
  - sudo apt-get install python-dev swig
  - sudo pip install nose
  - sudo pip install coveralls --use-mirrors
script: make 
script: make test
after_success:
  - make coverage
  - coveralls

